CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Human                       MKWVWALLLLAAL------GSGRAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLF
Cavia                       --MGMMLLLLSMLAGLVAEAEGQAFHFGKCPNPPVQENFDLNKYLGRWYEI-EKIPVSFE
Urocitellus                 --MAKMLLLLSALLGLFSAARGQTFHLGKCPTPPVQEYFDVTKYLGRWYEI-EKIPVSFE
Ictidomys                  --MTKMLLLLSALLGLFSTARGQTFHLGKCPTPPVQEYFDVTKYLGRWYEI-EKIPVSFE
Marmota                    --MAKMLLLLSALLGLFSAAKGQTFHLGKCPTPPVQEYFDVTKYLGRWYEI-EKIPVSFE
Marmota|XP_015342331.1      --MAKMLLLLSALLGLFSAAKGQTFHLGKCPTPPVQEYFDVTKYLGRWYEI-EKIPVSFE
                                  ****: *      . *.: .  . ..  *:* **  .: * ** : :* * .: 

Human                       LQDNIVAEFSVDETGQMSATAKGRVRLLNN---WDVCADMV---GTFTDTEDPAKFKMKY
Cavia                       KGNCIQANYSLKEN--------GRVKVLNQELRPDGTVNQIEGEATHSNITEPAKLGVKF
Urocitellus                 KGKCIQANYSLMET--------GKIKVLNQELRYDGTVNQIEGEAMVYNLTEPAKLGVKF
Ictidomys                  KGKCIQANYSLMET--------GKIKVLNQELRYDGTVNQIEGEAIVYNLTEPAKLGVKF
Marmota                    KGKCIQANYSLMET--------GKVKVLNQELRYDGTVNQIEGEATVYNLSEPAKLGVKF
Marmota|XP_015342331.1      KGKCIQANYSLMET--------GKIKVLNQELRYDGTVNQIEGEATVYNLTEPAKLGVKF
                              . * *::*: *.        *.:.:**:    *  .: :   .   :  :***: :*:

Human                       WGVASFLQKGNDDHWIVDTDYDTYAVQYSCR----LLNLDGTCADSYSFVFSRDPNGLPP
Cavia                       FQLMP-----SAPYWVLATDYDNYALVYSCTNIIWLFHVDHI------WILGRNRY-LPQ
Urocitellus                 FQLMP-----SAPYWVLATDYESYALVYSCTTIIWLFHLDHV------WILGRNPY-LPQ
Ictidomys                  SQLMP-----SAPYWVLATDYENYALVYSCTTIIWLFHLDHV------WILGRNPY-LPQ
Marmota                    SQLMP-----SAPYWVLATDYENYALVYSCTTIIWLFHLDHV------WILGRNPY-LPQ
Marmota|XP_015342331.1      SQLMP-----SAPYWVLATDYENYALVYSCTTIIWLFHLDHV------WILGRNPY-LPQ
                              : .     .  :*:: ***:.**: ***     *:::*        :::.*:   ** 

Human                       EAQKIVRQRQEELCLARQYRLIVHNGYCDGRSERNLL
Cavia                       ETVTYLKDILTSNNIDIEKMTLTDQANCPDFL-----
Urocitellus                 ETVTYLKSILTSNNISIEKMTKTDQENCPEFLGRGS-
Ictidomys                  ETVTYLKSILTSNNISIEKMTKTDQENCPEFLGRGS-
Marmota                    ETVTYLKSILTSNNISIEKMTKTDQENCPEFLGGGL-
Marmota|XP_015342331.1      ETVTYLKSILTSNNISIEKMTKTDQENCPEFLGGGF-
                            *: . :..   .  :  :    . :  *         
