>Human
MKWVWALLLLAAL------GSGRAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLF
LQDNIVAEFSVDETGQMSATAKGRVRLLNN---WDVCADMV---GTFTDTEDPAKFKMKY
WGVASFLQKGNDDHWIVDTDYDTYAVQYSCR----LLNLDGTCADSYSFVFSRDPNGLPP
EAQKIVRQRQEELCLARQYRLIVHNGYCDGRSERNLL
>Cavia
--MGMMLLLLSMLAGLVAEAEGQAFHFGKCPNPPVQENFDLNKYLGRWYEI-EKIPVSFE
KGNCIQANYSLKEN--------GRVKVLNQELRPDGTVNQIEGEATHSNITEPAKLGVKF
FQLMP-----SAPYWVLATDYDNYALVYSCTNIIWLFHVDHI------WILGRNRY-LPQ
ETVTYLKDILTSNNIDIEKMTLTDQANCPDFL-----
>Urocitellus
--MAKMLLLLSALLGLFSAARGQTFHLGKCPTPPVQEYFDVTKYLGRWYEI-EKIPVSFE
KGKCIQANYSLMET--------GKIKVLNQELRYDGTVNQIEGEAMVYNLTEPAKLGVKF
FQLMP-----SAPYWVLATDYESYALVYSCTTIIWLFHLDHV------WILGRNPY-LPQ
ETVTYLKSILTSNNISIEKMTKTDQENCPEFLGRGS-
>Ictidomys__________________-
-MTKMLLLLSALLGLFSTARGQTFHLGKCPTPPVQEYFDVTKYLGRWYEI-EKIPVSFE

GKCIQANYSLMET--------GKIKVLNQELRYDGTVNQIEGEAIVYNLTEPAKLGVKF

QLMP-----SAPYWVLATDYENYALVYSCTTIIWLFHLDHV------WILGRNPY-LPQ

TVTYLKSILTSNNISIEKMTKTDQENCPEFLGRGS-

>Marmota____________________-
-MAKMLLLLSALLGLFSAAKGQTFHLGKCPTPPVQEYFDVTKYLGRWYEI-EKIPVSFE

GKCIQANYSLMET--------GKVKVLNQELRYDGTVNQIEGEATVYNLSEPAKLGVKF

QLMP-----SAPYWVLATDYENYALVYSCTTIIWLFHLDHV------WILGRNPY-LPQ

TVTYLKSILTSNNISIEKMTKTDQENCPEFLGGGL-

>Marmota|XP_015342331.1
--MAKMLLLLSALLGLFSAAKGQTFHLGKCPTPPVQEYFDVTKYLGRWYEI-EKIPVSFE
KGKCIQANYSLMET--------GKIKVLNQELRYDGTVNQIEGEATVYNLTEPAKLGVKF
SQLMP-----SAPYWVLATDYENYALVYSCTTIIWLFHLDHV------WILGRNPY-LPQ
ETVTYLKSILTSNNISIEKMTKTDQENCPEFLGGGF-
